const core = require("@actions/core");
const fs = require("fs");
require('dotenv').config();
const openai = require("openai");

const descriptions = core.getInput("descriptions") || process.env.descriptions;

const OPENAI_API_MODEL = core.getInput("OPENAI_API_MODEL") || process.env.OPENAI_API_MODEL;

const OPENAI_API_ORGANIZATION_ID = core.getInput("OPENAI_API_ORGANIZATION_ID") || process.env.OPENAI_API_ORGANIZATION_ID;

const OPENAI_API_PROJECT_ID = core.getInput("OPENAI_API_PROJECT_ID") || process.env.OPENAI_API_PROJECT_ID;

const OPENAI_API_TEMPERATURE = 0.5;

const OPENAI_API_TOKEN = core.getInput("OPENAI_API_TOKEN") || process.env.OPENAI_API_TOKEN;

function validateInputs() {
  let isError = false;
  const errors = [];

  if (!OPENAI_API_ORGANIZATION_ID) {
    errors.push('Missing OPENAI_API_ORGANIZATION_ID input');
    isError = true;
  }

  if (!OPENAI_API_PROJECT_ID) {
    errors.push('Missing OPENAI_API_PROJECT_ID input');
    isError = true;
  }

  if (!OPENAI_API_TOKEN) {
    errors.push('Missing OPENAI_API_TOKEN input');
    isError = true;
  }

  if (isError) {
    core.error("Input validation errors");
    core.setFailed(errors.join("\n"));
    process.exit();
  }
}

function debugMessages() {
  core.startGroup("Debug messages");
  core.info(`OPENAI_API_MODEL: ${OPENAI_API_MODEL}`);
  core.info(`Descriptions: ${descriptions}`);
  core.endGroup();
}

async function generateFiles() {
  try {
    const _openai = new openai({
      apiKey: OPENAI_API_TOKEN,
      organization: OPENAI_API_ORGANIZATION_ID,
      project: OPENAI_API_PROJECT_ID,
      temperature: OPENAI_API_TEMPERATURE,
    });
  
    const completion = await _openai.chat.completions.create({
      messages: [
        {
          role: "system",
          content: `
            You are a very helpful developer. Your job is to write code. Your goal is to make code that is production ready.
            
            Your Task: 
            1. Stick to the descriptions provided below, don't add anything else.
            2. Use the minimum amount of required files.
            3. Make the minimum amount of assumptions about the rest of the repository.
            4. Provide the information as a compact, JSON-formatted array response.
            5. Each object should contain a 'filename' key, and the contents of the file should be in a 'content' key.
            
            Expected Output (in JSON format):
            [
              {
                "filename": "the/path/to/file.txt",
                "content": "The code contents of the file"
              }
            ]

            Your descriptions are: ${descriptions}`,
        },
      ],
      model: OPENAI_API_MODEL,
      response_format: {
        type: "json_object",
      },
    });

    if (completion.error) {
      core.error(completion.error);
      core.setFailed(completion.error.message);
      process.exit();
    }

    else {
      core.startGroup("OpenAI choices response");
      core.info(JSON.stringify(completion.choices));
      core.endGroup();
    }
    
    const files = JSON.parse(completion.choices[0].message.content).response;
    core.startGroup("Files generated by OpenAI");
    core.info(JSON.stringify(files));
    core.endGroup();
    return files;
  } catch (error) {
    core.setFailed(error.message);
  }
}

function writeFilesToRepository(files) {
  for (const file of files) {
    try {
      // File path
      let filePath = file.filename.lastIndexOf("/") > 0 ? file.filename.substring(0, file.filename.lastIndexOf("/") + 1) : "";
      filePath = filePath.indexOf("/") === 0 ? filePath.substring(1) : filePath;
      if (filePath.length > 0 && !fs.existsSync(filePath)) {
        fs.mkdirSync(filePath, { recursive: true });
      }

      // File name
      const fileName = file.filename.substring(file.filename.lastIndexOf("/") + 1);

      // File content
      const filePathAndName = `${filePath}${fileName}`;
      file.filename = filePathAndName;
      fs.writeFileSync(filePathAndName, file.content);

      // Debug
      core.startGroup(`File written to repository: ${filePathAndName}`);
      core.info(file.content);
      core.endGroup();
    } catch (error) {
      console.error(error);
      core.setFailed(error.message);
      process.exit();
    }
  }

  core.setOutput("files", files.map(file => file.filename).join("\n"));
}

async function run() {
  validateInputs();
  debugMessages();

  const files = await generateFiles();
  // TODO: Validate the response is valid JSON and the response structure we're expecting
  writeFilesToRepository(files);
}

run();
