name: Run Action

on:
  workflow_call:
    secrets:
      OPENAI_API_ORGANIZATION_ID:
        required: true
      OPENAI_API_PROJECT_ID:
        required: true
      OPENAI_API_TOKEN:
        required: true
        
    inputs:
      descriptions:
        description: 'Descriptions determine what files you want to be generated'
        required: true
        type: string

jobs:
  test:
    name: Run Action

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Action
      id: main
      uses: ./
      with:
        descriptions: "${{ github.event.inputs.descriptions }}"
        OPENAI_API_MODEL: ${{ vars.OPENAI_API_MODEL }}
        OPENAI_API_ORGANIZATION_ID: ${{ secrets.OPENAI_API_ORGANIZATION_ID }}
        OPENAI_API_PROJECT_ID: ${{ secrets.OPENAI_API_PROJECT_ID }}
        OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}

    - name: Create Pull Request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v7
      with:
        add-paths: ${{ steps.main.outputs.files }}
        base: main
        body: |
          This PR was automatically generated by the [ChatGPT GitHub Actions Bot](https://github.com/dallasclark/chatgpt-github-actions-bot) with descriptions: ${{ github.event.inputs.descriptions }}.
        branch: chatgpt-github-actions-bot/patch
        branch-suffix: timestamp
        delete-branch: true
        draft: false
        labels: |
          Automated PR
          Bot
          chatgpt-github-actions-bot
        title: "Automated Pull Request"
        token: ${{ secrets.PULL_REQUEST_TOKEN }}
