name: Run Action

on:
  workflow_call:
    secrets:
      OPENAI_API_ORGANIZATION_ID:
        required: true
      OPENAI_API_PROJECT_ID:
        required: true
      OPENAI_API_TOKEN:
        required: true
    inputs:
      descriptions:
        description: 'Descriptions determine what files you want to be generated'
        required: true
        type: string

jobs:
  test:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Action
      id: main
      uses: ./
      with:
        descriptions: ${{ github.event.inputs.descriptions || 'In the "/test/blog-articles" directory, I want you to generate two blog articles. The articles should be at least 200 words long, and should be less than 1000 characters long. The format should be markdown, and should not contain any HTML. The articles should be about automated testing and the importance setting up a great testing framework, with one automated testing topic per article.' }}
        OPENAI_API_MODEL: ${{ vars.OPENAI_API_MODEL }}
        OPENAI_API_ORGANIZATION_ID: ${{ secrets.OPENAI_API_ORGANIZATION_ID }}
        OPENAI_API_PROJECT_ID: ${{ secrets.OPENAI_API_PROJECT_ID }}
        OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}

    - name: Output Action
      run: |
        echo "The files written are:"
        echo ${{ steps.main.outputs.files }}