name: Run Action

on:
  workflow_call:
    secrets:
      OPENAI_API_ORGANIZATION_ID:
        required: true
      OPENAI_API_PROJECT_ID:
        required: true
      OPENAI_API_TOKEN:
        required: true
    inputs:
      descriptions:
        description: 'Descriptions determine what files you want to be generated'
        required: true
        type: string

jobs:
  test:
    name: Run Action

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Action
      id: main
      uses: ./
      with:
        descriptions: ${{ github.event.inputs.descriptions || 'In the "/test/blog-articles" directory, I want you to generate two blog articles. The articles should be at least 200 words long, and should be less than 1000 characters long. The format should be markdown, and should not contain any HTML. The articles should be about automated testing and the importance setting up a great testing framework, with one automated testing topic per article.' }}
        OPENAI_API_MODEL: ${{ vars.OPENAI_API_MODEL }}
        OPENAI_API_ORGANIZATION_ID: ${{ secrets.OPENAI_API_ORGANIZATION_ID }}
        OPENAI_API_PROJECT_ID: ${{ secrets.OPENAI_API_PROJECT_ID }}
        OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}

    # - name: Output Action
    #   run: |
    #     echo "The files written are:"
    #     echo "${{ steps.main.outputs.files }}"

    - name: Create Pull Request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v7
      with:
        add-paths: ${{ steps.main.outputs.files }}
        base: develop
        body: |
          This PR was automatically generated by the [ChatGPT GitHub Actions Bot](https://github.com/dallasclark/chatgpt-github-actions-bot) with descriptions: ${{ github.event.inputs.descriptions }}.
        branch: chatgpt-github-actions-bot/patch
        branch-suffix: timestamp
        delete-branch: true
        draft: false
        labels: |
          Automated PR
          Bot
          chatgpt-github-actions-bot
        title: "Automated Pull Request"
        token: ${{ secrets.PULL_REQUEST_TOKEN }}